version: 2.1
jobs:
  build:
    environment:
      GO111MODULE: "on"
      CONSUL_VERSION: 1.6.1
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/hashicorp/consul-esm
    steps:
      - checkout
      - restore_cache:
          keys:
          - ct-modcache-v1-{{ checksum "go.mod" }}
      - run: |
          curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
          unzip consul.zip
          sudo cp consul /usr/local/bin/
      - run: |
          make test
      - save_cache:
          key: ct-modcache-v1-{{ checksum "go.mod" }}
          paths:
          - /go/pkg/mod

